# Generated by Django 5.2.3 on 2025-07-06 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile_city_profile_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='created_at',
        ),
    ]
