# Generated by Django 5.2.3 on 2025-07-11 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_profiletheme_profile_cover_profile_theme_story_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='theme',
        ),
        migrations.RemoveField(
            model_name='story',
            name='post',
        ),
        migrations.RemoveField(
            model_name='story',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userbadge',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='cover',
        ),
        migrations.AddField(
            model_name='profile',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.DeleteModel(
            name='ProfileTheme',
        ),
        migrations.DeleteModel(
            name='Story',
        ),
        migrations.DeleteModel(
            name='UserBadge',
        ),
    ]
